DWES/django/ejer2/ciclos/urls.py
from django.urls import path

from . import views

app_name = 'ciclos'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

DWES/django/ejer2/ejer2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ejer2/', include('ciclos.urls')),
    path('admin/', admin.site.urls),
]

DWES/django/ejer2/ciclos/models.py
from django.db import models

# Create your models here.

class Familia (models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre
    
class Ciclo (models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    familia = models.ForeignKey(Familia, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

DWES/django/ejer2/ciclos/views.py
from django.shortcuts import render

from django.views import generic

from .models import Familia

class IndexView(generic.ListView):
    model = Familia
    template_name = 'ciclos/index.html'
    context_object_name = 'familias'

    
class DetailView(generic.DetailView):
    model = Familia
    template_name = 'ciclos/detail.html'
    context_object_name = 'familia' 

DWES/django/ejer2/ciclos/templates/ciclos/detail.html
{% if familia %}
    <h1>{{ familia.nombre }}</h1>
    <p>{{ familia.descripcion }}</p>
    <ul>
        {% for ciclo in familia.ciclo_set.all %}
            <li>{{ ciclo.nombre }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No existe la familia</p>
{% endif %}

DWES/django/ejer2/ciclos/templates/ciclos/index.html
{% if familias%}
    <h1>Lista de familias</h1>
    <ul>
        {% for familia in familias %}
            <li><a href="{% url 'ciclos:detail' pk=familia.id %}">{{ familia.nombre }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay familias</p>
{% endif %}